# Generated by Django 2.1.3 on 2018-11-12 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('todo', 'todo'), ('in-progress', 'in-progress'), ('done', 'done')], max_length=254)),
                ('due_date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
    ]
